### PR TITLE
Use libpng dll for windows instead

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
@Jupeyy is that better?

**Comment by Jupeyy** [comment]
I think this works too, should we maybe remove the `-16` from the name?

probs makes it easier to update in future

**Comment by Jupeyy** [comment]
> I think this works too, should we maybe remove the `-16` from the name?
> 
> probs makes it easier to update in future

Ah but i guess the .lib contains the .dll name so doesnt work anyway

**Comment by Jupeyy** [comment]
Well then lets just try it with the suffix, before we wait another year

**Pull request merged**
