### PR TITLE
SDL2 2.0.16 -> 2.0.18 (still with patches)

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Jupeyy** [comment]
I recently forced pushed the 2nd patch as a result of the discussion inside the pr, it's currently completly untested. I hoped SDL would fix the relative mouse mode bugs under windows in 2.0.18 already, which they delayed to 2.0.20.

But i also don't want to give any support for this anymore, there is always some bug on some system and that's kinda annoying.

So if you want to use 2.0.18 you could either:
- try the patch and see if it just works:tm:
- or dont use the patch and remove the commeted out code in input.cpp and set SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS hint to 1 on windows, so it always minimizes the app, which won't result in any bug(as its the same behavior before 2.0.16)

**Comment by def-** [comment]
> I recently forced pushed the 2nd patch as a result of the discussion inside the pr, it's currently completly untested

I took the old version ;)

**Comment by def-** [comment]
So can we get this in as is? Seems to fix some stuff on macOS

**Comment by def-** [comment]
@Jupeyy ?

**Comment by Jupeyy** [comment]
I said i wont give support for this anymore, sorry.

**Pull request merged**
